[buildpack]
id = "org.cloudfoundry.php-composer"
name = "PHP Composer Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.dependencies]]
id = "php-composer"
name = "Composer"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
sha256 = "23b29b1a921b56db3c12ba531752dffcfaa3de0fcece3e54974e06990e46bbf9"
uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer-1.8.5-23b29b1a.phar"
version = "1.8.5"
source = "https://github.com/composer/composer/releases/download/1.8.5/composer.phar"
source_sha256 = "23b29b1a921b56db3c12ba531752dffcfaa3de0fcece3e54974e06990e46bbf9"
