api = "0.2"

[buildpack]
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/php-composer"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "72a5a68d12f315d74d931462413f7e114cd77b4be1a6b9494141dda93410751a"
    source = "https://github.com/composer/composer/releases/download/2.0.10/composer.phar"
    source_sha256 = "72a5a68d12f315d74d931462413f7e114cd77b4be1a6b9494141dda93410751a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.0.10_linux_noarch_any-stack_72a5a68d.phar"
    version = "2.0.10"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "d6eee0d4637f4bd82bdae098fceda300dcb3ec35bf502604fbe7510933b8f952"
    source = "https://github.com/composer/composer/releases/download/2.0.11/composer.phar"
    source_sha256 = "d6eee0d4637f4bd82bdae098fceda300dcb3ec35bf502604fbe7510933b8f952"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.0.11_linux_noarch_any-stack_d6eee0d4.phar"
    version = "2.0.11"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
