api = "0.2"

[buildpack]
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/php-composer"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "e786d1d997efc1eb463d7447394b6ad17a144afcf8e505a3ce3cb0f60c3302f9"
    source = "https://github.com/composer/composer/releases/download/2.0.5/composer.phar"
    source_sha256 = "e786d1d997efc1eb463d7447394b6ad17a144afcf8e505a3ce3cb0f60c3302f9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.0.5_linux_noarch_any-stack_e786d1d9.phar"
    version = "2.0.5"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "e5e39d8fa699ddb09844f6b4388280ff2c805fef0a7c26580c5bbc91ac35091b"
    source = "https://github.com/composer/composer/releases/download/2.0.6/composer.phar"
    source_sha256 = "e5e39d8fa699ddb09844f6b4388280ff2c805fef0a7c26580c5bbc91ac35091b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.0.6_linux_noarch_any-stack_e5e39d8f.phar"
    version = "2.0.6"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
