api = "0.2"

[buildpack]
  id = "paketo-buildpacks/php-composer"
  name = "PHP Composer Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "57c63365eccdd4a787ebc40b9c57a4e019ab79d2f8662cea9892992d91640bf0"
    source = "https://github.com/composer/composer/releases/download/1.10.1/composer.phar"
    source_sha256 = "57c63365eccdd4a787ebc40b9c57a4e019ab79d2f8662cea9892992d91640bf0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer-1.10.1-57c63365.phar"
    version = "1.10.1"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "6a2c0ba6cdd50b66516bf33554cbcf222b95799e9bacf2687adbe7e59f3bbad0"
    source = "https://github.com/composer/composer/releases/download/1.10.4/composer.phar"
    source_sha256 = "6a2c0ba6cdd50b66516bf33554cbcf222b95799e9bacf2687adbe7e59f3bbad0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_1.10.4_linux_noarch_any-stack_6a2c0ba6.phar"
    version = "1.10.4"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
