api = "0.2"

[buildpack]
  id = "paketo-buildpacks/php-composer"
  name = "Paketo PHP Composer Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/php-composer"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "c3b2bc477429c923c69f7f9b137e06b2a93c6a1e192d40ffad1741ee5d54760d"
    source = "https://github.com/composer/composer/releases/download/2.0.4/composer.phar"
    source_sha256 = "c3b2bc477429c923c69f7f9b137e06b2a93c6a1e192d40ffad1741ee5d54760d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.0.4_linux_noarch_any-stack_c3b2bc47.phar"
    version = "2.0.4"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "e786d1d997efc1eb463d7447394b6ad17a144afcf8e505a3ce3cb0f60c3302f9"
    source = "https://github.com/composer/composer/releases/download/2.0.5/composer.phar"
    source_sha256 = "e786d1d997efc1eb463d7447394b6ad17a144afcf8e505a3ce3cb0f60c3302f9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_2.0.5_linux_noarch_any-stack_e786d1d9.phar"
    version = "2.0.5"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
