api = "0.2"

[buildpack]
  id = "paketo-buildpacks/php-composer"
  name = "PHP Composer Buildpack"
  version = "{{ .Version }}"
  homepage = "https://github.com/paketo-buildpacks/php-composer"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml"]
  pre_package = "./scripts/build.sh"
  [metadata.default-versions]
    composer = "*"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "6a2c0ba6cdd50b66516bf33554cbcf222b95799e9bacf2687adbe7e59f3bbad0"
    source = "https://github.com/composer/composer/releases/download/1.10.4/composer.phar"
    source_sha256 = "6a2c0ba6cdd50b66516bf33554cbcf222b95799e9bacf2687adbe7e59f3bbad0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_1.10.4_linux_noarch_any-stack_6a2c0ba6.phar"
    version = "1.10.4"

  [[metadata.dependencies]]
    id = "composer"
    sha256 = "a1f79ebd0cdc6980ad0fe11fef5b1b02c96c1dbec383d81b750a214c5a79ded0"
    source = "https://github.com/composer/composer/releases/download/1.10.5/composer.phar"
    source_sha256 = "a1f79ebd0cdc6980ad0fe11fef5b1b02c96c1dbec383d81b750a214c5a79ded0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/composer/composer_1.10.5_linux_noarch_any-stack_a1f79ebd.phar"
    version = "1.10.5"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
